using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;
using OpusLink.Entity.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OpusLink.Entity.Configurations
{
    public class ChatBoxConfiguration : IEntityTypeConfiguration<ChatBox>
    {
        public void Configure(EntityTypeBuilder<ChatBox> builder)
        {
            builder.ToTable("ChatBox");
            builder.HasKey(x => x.ChatBoxID);
            builder.Property(x => x.ChatBoxID).ValueGeneratedOnAdd();
            builder.Property(x => x.IsViewed).IsRequired();
            builder.HasOne(x => x.Employer).WithMany(x => x.ChatBoxsAsAnEmployer).HasForeignKey(x => x.EmployerID).OnDelete(DeleteBehavior.Restrict);
            builder.HasOne(x => x.Freelancer).WithMany(x => x.ChatBoxsAsAFreelancer).HasForeignKey(x => x.FreelancerID).OnDelete(DeleteBehavior.Restrict); 
            builder.HasOne(x => x.Job).WithMany(x => x.ChatBoxes).HasForeignKey(x => x.JobID).OnDelete(DeleteBehavior.Restrict); 
            builder.HasData(
new ChatBox { ChatBoxID = 1, JobID = 4, EmployerID = 42, FreelancerID = 120, IsViewed = true },
new ChatBox { ChatBoxID = 2, JobID = 5, EmployerID = 64, FreelancerID = 111, IsViewed = true },
new ChatBox { ChatBoxID = 3, JobID = 6, EmployerID = 64, FreelancerID = 140, IsViewed = true },
new ChatBox { ChatBoxID = 4, JobID = 7, EmployerID = 61, FreelancerID = 115, IsViewed = true },
new ChatBox { ChatBoxID = 5, JobID = 8, EmployerID = 99, FreelancerID = 141, IsViewed = true },
new ChatBox { ChatBoxID = 6, JobID = 9, EmployerID = 30, FreelancerID = 142, IsViewed = true },
new ChatBox { ChatBoxID = 7, JobID = 10, EmployerID = 72, FreelancerID = 145, IsViewed = true },
new ChatBox { ChatBoxID = 8, JobID = 11, EmployerID = 41, FreelancerID = 103, IsViewed = true },
new ChatBox { ChatBoxID = 9, JobID = 12, EmployerID = 47, FreelancerID = 146, IsViewed = true },
new ChatBox { ChatBoxID = 10, JobID = 13, EmployerID = 83, FreelancerID = 147, IsViewed = true },
new ChatBox { ChatBoxID = 11, JobID = 14, EmployerID = 59, FreelancerID = 115, IsViewed = true },
new ChatBox { ChatBoxID = 12, JobID = 15, EmployerID = 20, FreelancerID = 148, IsViewed = true },
new ChatBox { ChatBoxID = 13, JobID = 16, EmployerID = 88, FreelancerID = 149, IsViewed = true },
new ChatBox { ChatBoxID = 14, JobID = 17, EmployerID = 99, FreelancerID = 150, IsViewed = true },
new ChatBox { ChatBoxID = 15, JobID = 18, EmployerID = 31, FreelancerID = 151, IsViewed = true },
new ChatBox { ChatBoxID = 16, JobID = 19, EmployerID = 58, FreelancerID = 152, IsViewed = true },
new ChatBox { ChatBoxID = 17, JobID = 20, EmployerID = 43, FreelancerID = 153, IsViewed = true },
new ChatBox { ChatBoxID = 18, JobID = 4, EmployerID = 42, FreelancerID = 154, IsViewed = true },
new ChatBox { ChatBoxID = 19, JobID = 5, EmployerID = 64, FreelancerID = 155, IsViewed = true },
new ChatBox { ChatBoxID = 20, JobID = 6, EmployerID = 64, FreelancerID = 156, IsViewed = true },
new ChatBox { ChatBoxID = 21, JobID = 7, EmployerID = 61, FreelancerID = 157, IsViewed = true },
new ChatBox { ChatBoxID = 22, JobID = 8, EmployerID = 99, FreelancerID = 103, IsViewed = true },
new ChatBox { ChatBoxID = 23, JobID = 9, EmployerID = 30, FreelancerID = 158, IsViewed = true },
new ChatBox { ChatBoxID = 24, JobID = 10, EmployerID = 72, FreelancerID = 115, IsViewed = true },
new ChatBox { ChatBoxID = 25, JobID = 11, EmployerID = 41, FreelancerID = 123, IsViewed = true },
new ChatBox { ChatBoxID = 26, JobID = 12, EmployerID = 47, FreelancerID = 122, IsViewed = true },
new ChatBox { ChatBoxID = 27, JobID = 13, EmployerID = 83, FreelancerID = 113, IsViewed = true },
new ChatBox { ChatBoxID = 28, JobID = 14, EmployerID = 59, FreelancerID = 121, IsViewed = true },
new ChatBox { ChatBoxID = 29, JobID = 15, EmployerID = 20, FreelancerID = 110, IsViewed = true },
new ChatBox { ChatBoxID = 30, JobID = 16, EmployerID = 88, FreelancerID = 120, IsViewed = true },
new ChatBox { ChatBoxID = 31, JobID = 17, EmployerID = 99, FreelancerID = 119, IsViewed = true },
new ChatBox { ChatBoxID = 32, JobID = 18, EmployerID = 31, FreelancerID = 118, IsViewed = true },
new ChatBox { ChatBoxID = 33, JobID = 19, EmployerID = 58, FreelancerID = 104, IsViewed = true },
new ChatBox { ChatBoxID = 34, JobID = 20, EmployerID = 43, FreelancerID = 101, IsViewed = true },
new ChatBox { ChatBoxID = 35, JobID = 4, EmployerID = 42, FreelancerID = 117, IsViewed = true },
new ChatBox { ChatBoxID = 36, JobID = 5, EmployerID = 64, FreelancerID = 116, IsViewed = true },
new ChatBox { ChatBoxID = 37, JobID = 6, EmployerID = 64, FreelancerID = 103, IsViewed = true },
new ChatBox { ChatBoxID = 38, JobID = 7, EmployerID = 61, FreelancerID = 102, IsViewed = true },
new ChatBox { ChatBoxID = 39, JobID = 8, EmployerID = 99, FreelancerID = 104, IsViewed = true },
new ChatBox { ChatBoxID = 40, JobID = 9, EmployerID = 30, FreelancerID = 115, IsViewed = true },
new ChatBox { ChatBoxID = 41, JobID = 10, EmployerID = 72, FreelancerID = 114, IsViewed = true },
new ChatBox { ChatBoxID = 42, JobID = 11, EmployerID = 41, FreelancerID = 101, IsViewed = true },
new ChatBox { ChatBoxID = 43, JobID = 12, EmployerID = 47, FreelancerID = 113, IsViewed = true },
new ChatBox { ChatBoxID = 44, JobID = 13, EmployerID = 83, FreelancerID = 112, IsViewed = true },
new ChatBox { ChatBoxID = 45, JobID = 14, EmployerID = 59, FreelancerID = 106, IsViewed = true },
new ChatBox { ChatBoxID = 46, JobID = 15, EmployerID = 20, FreelancerID = 103, IsViewed = true },
new ChatBox { ChatBoxID = 47, JobID = 16, EmployerID = 88, FreelancerID = 110, IsViewed = true },
new ChatBox { ChatBoxID = 48, JobID = 17, EmployerID = 99, FreelancerID = 101, IsViewed = true },
new ChatBox { ChatBoxID = 49, JobID = 18, EmployerID = 31, FreelancerID = 109, IsViewed = true },
new ChatBox { ChatBoxID = 50, JobID = 19, EmployerID = 58, FreelancerID = 112, IsViewed = true },
new ChatBox { ChatBoxID = 51, JobID = 20, EmployerID = 43, FreelancerID = 102, IsViewed = true },
new ChatBox { ChatBoxID = 52, JobID = 4, EmployerID = 42, FreelancerID = 108, IsViewed = true },
new ChatBox { ChatBoxID = 53, JobID = 5, EmployerID = 64, FreelancerID = 107, IsViewed = true },
new ChatBox { ChatBoxID = 54, JobID = 6, EmployerID = 64, FreelancerID = 105, IsViewed = true },
new ChatBox { ChatBoxID = 55, JobID = 7, EmployerID = 61, FreelancerID = 107, IsViewed = true },
new ChatBox { ChatBoxID = 56, JobID = 8, EmployerID = 99, FreelancerID = 112, IsViewed = true },
new ChatBox { ChatBoxID = 57, JobID = 9, EmployerID = 30, FreelancerID = 112, IsViewed = true },
new ChatBox { ChatBoxID = 58, JobID = 10, EmployerID = 72, FreelancerID = 113, IsViewed = true },
new ChatBox { ChatBoxID = 59, JobID = 11, EmployerID = 41, FreelancerID = 114, IsViewed = true },
new ChatBox { ChatBoxID = 60, JobID = 12, EmployerID = 47, FreelancerID = 106, IsViewed = true },
new ChatBox { ChatBoxID = 61, JobID = 13, EmployerID = 83, FreelancerID = 106, IsViewed = true },
new ChatBox { ChatBoxID = 62, JobID = 14, EmployerID = 59, FreelancerID = 107, IsViewed = true },
new ChatBox { ChatBoxID = 63, JobID = 15, EmployerID = 20, FreelancerID = 131, IsViewed = true },
new ChatBox { ChatBoxID = 64, JobID = 16, EmployerID = 88, FreelancerID = 109, IsViewed = true },
new ChatBox { ChatBoxID = 65, JobID = 17, EmployerID = 99, FreelancerID = 132, IsViewed = true },
new ChatBox { ChatBoxID = 66, JobID = 18, EmployerID = 31, FreelancerID = 133, IsViewed = true },
new ChatBox { ChatBoxID = 67, JobID = 19, EmployerID = 58, FreelancerID = 134, IsViewed = true },
new ChatBox { ChatBoxID = 68, JobID = 20, EmployerID = 43, FreelancerID = 112, IsViewed = true },
new ChatBox { ChatBoxID = 69, JobID = 4, EmployerID = 42, FreelancerID = 107, IsViewed = true },
new ChatBox { ChatBoxID = 70, JobID = 5, EmployerID = 64, FreelancerID = 135, IsViewed = true },
new ChatBox { ChatBoxID = 71, JobID = 6, EmployerID = 64, FreelancerID = 136, IsViewed = true },
new ChatBox { ChatBoxID = 72, JobID = 7, EmployerID = 61, FreelancerID = 137, IsViewed = true },
new ChatBox { ChatBoxID = 73, JobID = 8, EmployerID = 99, FreelancerID = 101, IsViewed = true },
new ChatBox { ChatBoxID = 74, JobID = 9, EmployerID = 30, FreelancerID = 138, IsViewed = true },
new ChatBox { ChatBoxID = 75, JobID = 10, EmployerID = 72, FreelancerID = 101, IsViewed = true },
new ChatBox { ChatBoxID = 76, JobID = 11, EmployerID = 41, FreelancerID = 112, IsViewed = true },
new ChatBox { ChatBoxID = 77, JobID = 12, EmployerID = 47, FreelancerID = 101, IsViewed = true },
new ChatBox { ChatBoxID = 78, JobID = 13, EmployerID = 83, FreelancerID = 102, IsViewed = true },
new ChatBox { ChatBoxID = 79, JobID = 14, EmployerID = 59, FreelancerID = 105, IsViewed = true },
new ChatBox { ChatBoxID = 80, JobID = 15, EmployerID = 20, FreelancerID = 139, IsViewed = true },
new ChatBox { ChatBoxID = 81, JobID = 16, EmployerID = 88, FreelancerID = 107, IsViewed = true },
new ChatBox { ChatBoxID = 82, JobID = 17, EmployerID = 99, FreelancerID = 102, IsViewed = true },
new ChatBox { ChatBoxID = 83, JobID = 18, EmployerID = 31, FreelancerID = 107, IsViewed = true },
new ChatBox { ChatBoxID = 84, JobID = 19, EmployerID = 58, FreelancerID = 140, IsViewed = true },
new ChatBox { ChatBoxID = 85, JobID = 20, EmployerID = 43, FreelancerID = 141, IsViewed = true },
new ChatBox { ChatBoxID = 86, JobID = 4, EmployerID = 42, FreelancerID = 142, IsViewed = true },
new ChatBox { ChatBoxID = 87, JobID = 5, EmployerID = 64, FreelancerID = 143, IsViewed = true },
new ChatBox { ChatBoxID = 88, JobID = 6, EmployerID = 64, FreelancerID = 102, IsViewed = true },
new ChatBox { ChatBoxID = 89, JobID = 7, EmployerID = 61, FreelancerID = 106, IsViewed = true },
new ChatBox { ChatBoxID = 90, JobID = 8, EmployerID = 99, FreelancerID = 111, IsViewed = true },
new ChatBox { ChatBoxID = 91, JobID = 9, EmployerID = 30, FreelancerID = 103, IsViewed = true },
new ChatBox { ChatBoxID = 92, JobID = 10, EmployerID = 72, FreelancerID = 104, IsViewed = true },
new ChatBox { ChatBoxID = 93, JobID = 11, EmployerID = 41, FreelancerID = 106, IsViewed = true },
new ChatBox { ChatBoxID = 94, JobID = 12, EmployerID = 47, FreelancerID = 107, IsViewed = true },
new ChatBox { ChatBoxID = 95, JobID = 13, EmployerID = 83, FreelancerID = 103, IsViewed = true },
new ChatBox { ChatBoxID = 96, JobID = 14, EmployerID = 59, FreelancerID = 111, IsViewed = true },
new ChatBox { ChatBoxID = 97, JobID = 15, EmployerID = 20, FreelancerID = 108, IsViewed = true },
new ChatBox { ChatBoxID = 98, JobID = 16, EmployerID = 88, FreelancerID = 104, IsViewed = true },
new ChatBox { ChatBoxID = 99, JobID = 17, EmployerID = 99, FreelancerID = 109, IsViewed = true },
new ChatBox { ChatBoxID = 100, JobID = 18, EmployerID = 31, FreelancerID = 101, IsViewed = true },
new ChatBox { ChatBoxID = 101, JobID = 19, EmployerID = 58, FreelancerID = 108, IsViewed = false },
new ChatBox { ChatBoxID = 102, JobID = 20, EmployerID = 43, FreelancerID = 111, IsViewed = false },
new ChatBox { ChatBoxID = 103, JobID = 4, EmployerID = 42, FreelancerID = 106, IsViewed = false },
new ChatBox { ChatBoxID = 104, JobID = 5, EmployerID = 64, FreelancerID = 108, IsViewed = false },
new ChatBox { ChatBoxID = 105, JobID = 6, EmployerID = 64, FreelancerID = 111, IsViewed = false },
new ChatBox { ChatBoxID = 106, JobID = 7, EmployerID = 61, FreelancerID = 109, IsViewed = false },
new ChatBox { ChatBoxID = 107, JobID = 8, EmployerID = 99, FreelancerID = 109, IsViewed = false },
new ChatBox { ChatBoxID = 108, JobID = 9, EmployerID = 30, FreelancerID = 104, IsViewed = false },
new ChatBox { ChatBoxID = 109, JobID = 10, EmployerID = 72, FreelancerID = 111, IsViewed = false },
new ChatBox { ChatBoxID = 110, JobID = 11, EmployerID = 41, FreelancerID = 111, IsViewed = false },
new ChatBox { ChatBoxID = 111, JobID = 12, EmployerID = 47, FreelancerID = 111, IsViewed = false },
new ChatBox { ChatBoxID = 112, JobID = 13, EmployerID = 83, FreelancerID = 111, IsViewed = false },
new ChatBox { ChatBoxID = 113, JobID = 14, EmployerID = 59, FreelancerID = 102, IsViewed = false },
new ChatBox { ChatBoxID = 114, JobID = 15, EmployerID = 20, FreelancerID = 111, IsViewed = false },
new ChatBox { ChatBoxID = 115, JobID = 16, EmployerID = 88, FreelancerID = 105, IsViewed = false },
new ChatBox { ChatBoxID = 116, JobID = 17, EmployerID = 99, FreelancerID = 108, IsViewed = false },
new ChatBox { ChatBoxID = 117, JobID = 18, EmployerID = 31, FreelancerID = 108, IsViewed = false },
new ChatBox { ChatBoxID = 118, JobID = 19, EmployerID = 58, FreelancerID = 106, IsViewed = false },
new ChatBox { ChatBoxID = 119, JobID = 20, EmployerID = 43, FreelancerID = 108, IsViewed = false },
new ChatBox { ChatBoxID = 120, JobID = 4, EmployerID = 42, FreelancerID = 111, IsViewed = false },
new ChatBox { ChatBoxID = 121, JobID = 5, EmployerID = 64, FreelancerID = 103, IsViewed = false },
new ChatBox { ChatBoxID = 122, JobID = 6, EmployerID = 64, FreelancerID = 108, IsViewed = false },
new ChatBox { ChatBoxID = 123, JobID = 7, EmployerID = 61, FreelancerID = 103, IsViewed = false },
new ChatBox { ChatBoxID = 124, JobID = 8, EmployerID = 99, FreelancerID = 108, IsViewed = false },
new ChatBox { ChatBoxID = 125, JobID = 9, EmployerID = 30, FreelancerID = 111, IsViewed = false },
new ChatBox { ChatBoxID = 126, JobID = 10, EmployerID = 72, FreelancerID = 110, IsViewed = false },
new ChatBox { ChatBoxID = 127, JobID = 11, EmployerID = 41, FreelancerID = 109, IsViewed = false },
new ChatBox { ChatBoxID = 128, JobID = 12, EmployerID = 47, FreelancerID = 108, IsViewed = false },
new ChatBox { ChatBoxID = 129, JobID = 13, EmployerID = 83, FreelancerID = 108, IsViewed = false },
new ChatBox { ChatBoxID = 130, JobID = 14, EmployerID = 59, FreelancerID = 109, IsViewed = false },
new ChatBox { ChatBoxID = 131, JobID = 15, EmployerID = 20, FreelancerID = 107, IsViewed = false },
new ChatBox { ChatBoxID = 132, JobID = 16, EmployerID = 88, FreelancerID = 101, IsViewed = false },
new ChatBox { ChatBoxID = 133, JobID = 17, EmployerID = 99, FreelancerID = 110, IsViewed = false },
new ChatBox { ChatBoxID = 134, JobID = 18, EmployerID = 31, FreelancerID = 103, IsViewed = false },
new ChatBox { ChatBoxID = 135, JobID = 19, EmployerID = 58, FreelancerID = 110, IsViewed = false },
new ChatBox { ChatBoxID = 136, JobID = 20, EmployerID = 43, FreelancerID = 109, IsViewed = false },
new ChatBox { ChatBoxID = 137, JobID = 4, EmployerID = 42, FreelancerID = 102, IsViewed = false },
new ChatBox { ChatBoxID = 138, JobID = 5, EmployerID = 64, FreelancerID = 104, IsViewed = false },
new ChatBox { ChatBoxID = 139, JobID = 6, EmployerID = 64, FreelancerID = 107, IsViewed = false },
new ChatBox { ChatBoxID = 140, JobID = 7, EmployerID = 61, FreelancerID = 101, IsViewed = false },
new ChatBox { ChatBoxID = 141, JobID = 8, EmployerID = 99, FreelancerID = 106, IsViewed = false },
new ChatBox { ChatBoxID = 142, JobID = 9, EmployerID = 30, FreelancerID = 109, IsViewed = false },
new ChatBox { ChatBoxID = 143, JobID = 10, EmployerID = 72, FreelancerID = 109, IsViewed = false },
new ChatBox { ChatBoxID = 144, JobID = 11, EmployerID = 41, FreelancerID = 105, IsViewed = false },
new ChatBox { ChatBoxID = 145, JobID = 12, EmployerID = 47, FreelancerID = 103, IsViewed = false },
new ChatBox { ChatBoxID = 146, JobID = 13, EmployerID = 83, FreelancerID = 109, IsViewed = false },
new ChatBox { ChatBoxID = 147, JobID = 14, EmployerID = 59, FreelancerID = 104, IsViewed = false },
new ChatBox { ChatBoxID = 148, JobID = 15, EmployerID = 20, FreelancerID = 106, IsViewed = false },
new ChatBox { ChatBoxID = 149, JobID = 16, EmployerID = 88, FreelancerID = 102, IsViewed = false },
new ChatBox { ChatBoxID = 150, JobID = 17, EmployerID = 99, FreelancerID = 103, IsViewed = false },
new ChatBox { ChatBoxID = 151, JobID = 18, EmployerID = 31, FreelancerID = 104, IsViewed = false },
new ChatBox { ChatBoxID = 152, JobID = 19, EmployerID = 58, FreelancerID = 109, IsViewed = false },
new ChatBox { ChatBoxID = 153, JobID = 20, EmployerID = 43, FreelancerID = 104, IsViewed = false },
new ChatBox { ChatBoxID = 154, JobID = 4, EmployerID = 42, FreelancerID = 110, IsViewed = false },
new ChatBox { ChatBoxID = 155, JobID = 5, EmployerID = 64, FreelancerID = 109, IsViewed = false },
new ChatBox { ChatBoxID = 156, JobID = 6, EmployerID = 64, FreelancerID = 104, IsViewed = false },
new ChatBox { ChatBoxID = 157, JobID = 7, EmployerID = 61, FreelancerID = 110, IsViewed = false },
new ChatBox { ChatBoxID = 158, JobID = 8, EmployerID = 99, FreelancerID = 107, IsViewed = false },
new ChatBox { ChatBoxID = 159, JobID = 9, EmployerID = 30, FreelancerID = 108, IsViewed = false },
new ChatBox { ChatBoxID = 160, JobID = 10, EmployerID = 72, FreelancerID = 102, IsViewed = false },
new ChatBox { ChatBoxID = 161, JobID = 11, EmployerID = 41, FreelancerID = 110, IsViewed = false },
new ChatBox { ChatBoxID = 162, JobID = 12, EmployerID = 47, FreelancerID = 104, IsViewed = false },
new ChatBox { ChatBoxID = 163, JobID = 13, EmployerID = 83, FreelancerID = 101, IsViewed = false },
new ChatBox { ChatBoxID = 164, JobID = 14, EmployerID = 59, FreelancerID = 108, IsViewed = false },
new ChatBox { ChatBoxID = 165, JobID = 15, EmployerID = 20, FreelancerID = 102, IsViewed = false },
new ChatBox { ChatBoxID = 166, JobID = 16, EmployerID = 88, FreelancerID = 108, IsViewed = false },
new ChatBox { ChatBoxID = 167, JobID = 17, EmployerID = 99, FreelancerID = 107, IsViewed = false },
new ChatBox { ChatBoxID = 168, JobID = 18, EmployerID = 31, FreelancerID = 110, IsViewed = false },
new ChatBox { ChatBoxID = 169, JobID = 19, EmployerID = 58, FreelancerID = 107, IsViewed = false },
new ChatBox { ChatBoxID = 170, JobID = 20, EmployerID = 43, FreelancerID = 106, IsViewed = false },
new ChatBox { ChatBoxID = 171, JobID = 4, EmployerID = 42, FreelancerID = 109, IsViewed = false },
new ChatBox { ChatBoxID = 172, JobID = 5, EmployerID = 64, FreelancerID = 110, IsViewed = false },
new ChatBox { ChatBoxID = 173, JobID = 6, EmployerID = 64, FreelancerID = 106, IsViewed = false },
new ChatBox { ChatBoxID = 174, JobID = 7, EmployerID = 61, FreelancerID = 104, IsViewed = false },
new ChatBox { ChatBoxID = 175, JobID = 8, EmployerID = 99, FreelancerID = 110, IsViewed = false },
new ChatBox { ChatBoxID = 176, JobID = 9, EmployerID = 30, FreelancerID = 110, IsViewed = false },
new ChatBox { ChatBoxID = 177, JobID = 10, EmployerID = 72, FreelancerID = 105, IsViewed = false },
new ChatBox { ChatBoxID = 178, JobID = 11, EmployerID = 41, FreelancerID = 108, IsViewed = false },
new ChatBox { ChatBoxID = 179, JobID = 12, EmployerID = 47, FreelancerID = 102, IsViewed = false },
new ChatBox { ChatBoxID = 180, JobID = 13, EmployerID = 83, FreelancerID = 110, IsViewed = false },
new ChatBox { ChatBoxID = 181, JobID = 14, EmployerID = 59, FreelancerID = 101, IsViewed = false },
new ChatBox { ChatBoxID = 182, JobID = 15, EmployerID = 20, FreelancerID = 109, IsViewed = false },
new ChatBox { ChatBoxID = 183, JobID = 16, EmployerID = 88, FreelancerID = 103, IsViewed = false },
new ChatBox { ChatBoxID = 184, JobID = 17, EmployerID = 99, FreelancerID = 106, IsViewed = false },
new ChatBox { ChatBoxID = 185, JobID = 18, EmployerID = 31, FreelancerID = 106, IsViewed = false },
new ChatBox { ChatBoxID = 186, JobID = 19, EmployerID = 58, FreelancerID = 102, IsViewed = false },
new ChatBox { ChatBoxID = 187, JobID = 20, EmployerID = 43, FreelancerID = 103, IsViewed = false },
new ChatBox { ChatBoxID = 188, JobID = 4, EmployerID = 42, FreelancerID = 103, IsViewed = false },
new ChatBox { ChatBoxID = 189, JobID = 5, EmployerID = 64, FreelancerID = 106, IsViewed = false },
new ChatBox { ChatBoxID = 190, JobID = 6, EmployerID = 64, FreelancerID = 109, IsViewed = false },
new ChatBox { ChatBoxID = 191, JobID = 7, EmployerID = 61, FreelancerID = 108, IsViewed = false },
new ChatBox { ChatBoxID = 192, JobID = 8, EmployerID = 99, FreelancerID = 105, IsViewed = false },
new ChatBox { ChatBoxID = 193, JobID = 9, EmployerID = 30, FreelancerID = 106, IsViewed = false },
new ChatBox { ChatBoxID = 194, JobID = 10, EmployerID = 72, FreelancerID = 108, IsViewed = false },
new ChatBox { ChatBoxID = 195, JobID = 11, EmployerID = 41, FreelancerID = 102, IsViewed = false },
new ChatBox { ChatBoxID = 196, JobID = 12, EmployerID = 47, FreelancerID = 109, IsViewed = false },
new ChatBox { ChatBoxID = 197, JobID = 13, EmployerID = 83, FreelancerID = 107, IsViewed = false },
new ChatBox { ChatBoxID = 198, JobID = 14, EmployerID = 59, FreelancerID = 103, IsViewed = false },
new ChatBox { ChatBoxID = 199, JobID = 15, EmployerID = 20, FreelancerID = 105, IsViewed = false },
new ChatBox { ChatBoxID = 200, JobID = 16, EmployerID = 88, FreelancerID = 106, IsViewed = false }


);
        }
    }
}
