using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;
using OpusLink.Entity.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OpusLink.Entity.Configurations
{
    public class ChatBoxConfiguration : IEntityTypeConfiguration<ChatBox>
    {
        public void Configure(EntityTypeBuilder<ChatBox> builder)
        {
            builder.ToTable("ChatBox");
            builder.HasKey(x => x.ChatBoxID);
            builder.Property(x => x.ChatBoxID).ValueGeneratedOnAdd();
            builder.Property(x => x.IsViewed).IsRequired();
            builder.HasOne(x => x.Employer).WithMany(x => x.ChatBoxsAsAnEmployer).HasForeignKey(x => x.EmployerID).OnDelete(DeleteBehavior.Restrict);
            builder.HasOne(x => x.Freelancer).WithMany(x => x.ChatBoxsAsAFreelancer).HasForeignKey(x => x.FreelancerID).OnDelete(DeleteBehavior.Restrict); ;
            builder.HasData(
new ChatBox { ChatBoxID = 1, EmployerID = 36, FreelancerID = 109, IsViewed = true },
new ChatBox { ChatBoxID = 2, EmployerID = 24, FreelancerID = 106, IsViewed = true },
new ChatBox { ChatBoxID = 3, EmployerID = 35, FreelancerID = 107, IsViewed = true },
new ChatBox { ChatBoxID = 4, EmployerID = 33, FreelancerID = 107, IsViewed = true },
new ChatBox { ChatBoxID = 5, EmployerID = 39, FreelancerID = 101, IsViewed = true },
new ChatBox { ChatBoxID = 6, EmployerID = 35, FreelancerID = 106, IsViewed = true },
new ChatBox { ChatBoxID = 7, EmployerID = 21, FreelancerID = 108, IsViewed = true },
new ChatBox { ChatBoxID = 8, EmployerID = 22, FreelancerID = 103, IsViewed = true },
new ChatBox { ChatBoxID = 9, EmployerID = 39, FreelancerID = 101, IsViewed = true },
new ChatBox { ChatBoxID = 10, EmployerID = 25, FreelancerID = 108, IsViewed = true },
new ChatBox { ChatBoxID = 11, EmployerID = 20, FreelancerID = 109, IsViewed = true },
new ChatBox { ChatBoxID = 12, EmployerID = 21, FreelancerID = 102, IsViewed = true },
new ChatBox { ChatBoxID = 13, EmployerID = 24, FreelancerID = 104, IsViewed = true },
new ChatBox { ChatBoxID = 14, EmployerID = 29, FreelancerID = 108, IsViewed = true },
new ChatBox { ChatBoxID = 15, EmployerID = 25, FreelancerID = 106, IsViewed = true },
new ChatBox { ChatBoxID = 16, EmployerID = 20, FreelancerID = 110, IsViewed = true },
new ChatBox { ChatBoxID = 17, EmployerID = 35, FreelancerID = 104, IsViewed = true },
new ChatBox { ChatBoxID = 18, EmployerID = 23, FreelancerID = 103, IsViewed = true },
new ChatBox { ChatBoxID = 19, EmployerID = 26, FreelancerID = 106, IsViewed = true },
new ChatBox { ChatBoxID = 20, EmployerID = 30, FreelancerID = 104, IsViewed = true },
new ChatBox { ChatBoxID = 21, EmployerID = 37, FreelancerID = 102, IsViewed = true },
new ChatBox { ChatBoxID = 22, EmployerID = 25, FreelancerID = 103, IsViewed = true },
new ChatBox { ChatBoxID = 23, EmployerID = 22, FreelancerID = 110, IsViewed = true },
new ChatBox { ChatBoxID = 24, EmployerID = 23, FreelancerID = 104, IsViewed = true },
new ChatBox { ChatBoxID = 25, EmployerID = 23, FreelancerID = 108, IsViewed = true },
new ChatBox { ChatBoxID = 26, EmployerID = 26, FreelancerID = 103, IsViewed = true },
new ChatBox { ChatBoxID = 27, EmployerID = 27, FreelancerID = 108, IsViewed = true },
new ChatBox { ChatBoxID = 28, EmployerID = 38, FreelancerID = 107, IsViewed = true },
new ChatBox { ChatBoxID = 29, EmployerID = 27, FreelancerID = 110, IsViewed = true },
new ChatBox { ChatBoxID = 30, EmployerID = 24, FreelancerID = 102, IsViewed = true },
new ChatBox { ChatBoxID = 31, EmployerID = 26, FreelancerID = 102, IsViewed = true },
new ChatBox { ChatBoxID = 32, EmployerID = 40, FreelancerID = 106, IsViewed = true },
new ChatBox { ChatBoxID = 33, EmployerID = 38, FreelancerID = 104, IsViewed = true },
new ChatBox { ChatBoxID = 34, EmployerID = 24, FreelancerID = 101, IsViewed = true },
new ChatBox { ChatBoxID = 35, EmployerID = 27, FreelancerID = 107, IsViewed = true },
new ChatBox { ChatBoxID = 36, EmployerID = 27, FreelancerID = 110, IsViewed = true },
new ChatBox { ChatBoxID = 37, EmployerID = 33, FreelancerID = 103, IsViewed = true },
new ChatBox { ChatBoxID = 38, EmployerID = 28, FreelancerID = 102, IsViewed = true },
new ChatBox { ChatBoxID = 39, EmployerID = 40, FreelancerID = 104, IsViewed = true },
new ChatBox { ChatBoxID = 40, EmployerID = 24, FreelancerID = 104, IsViewed = true },
new ChatBox { ChatBoxID = 41, EmployerID = 32, FreelancerID = 109, IsViewed = true },
new ChatBox { ChatBoxID = 42, EmployerID = 38, FreelancerID = 101, IsViewed = true },
new ChatBox { ChatBoxID = 43, EmployerID = 32, FreelancerID = 104, IsViewed = true },
new ChatBox { ChatBoxID = 44, EmployerID = 37, FreelancerID = 101, IsViewed = true },
new ChatBox { ChatBoxID = 45, EmployerID = 39, FreelancerID = 108, IsViewed = true },
new ChatBox { ChatBoxID = 46, EmployerID = 32, FreelancerID = 103, IsViewed = true },
new ChatBox { ChatBoxID = 47, EmployerID = 33, FreelancerID = 101, IsViewed = true },
new ChatBox { ChatBoxID = 48, EmployerID = 24, FreelancerID = 101, IsViewed = true },
new ChatBox { ChatBoxID = 49, EmployerID = 39, FreelancerID = 107, IsViewed = true },
new ChatBox { ChatBoxID = 50, EmployerID = 32, FreelancerID = 110, IsViewed = true },
new ChatBox { ChatBoxID = 51, EmployerID = 20, FreelancerID = 102, IsViewed = true },
new ChatBox { ChatBoxID = 52, EmployerID = 40, FreelancerID = 110, IsViewed = true },
new ChatBox { ChatBoxID = 53, EmployerID = 39, FreelancerID = 107, IsViewed = true },
new ChatBox { ChatBoxID = 54, EmployerID = 35, FreelancerID = 105, IsViewed = true },
new ChatBox { ChatBoxID = 55, EmployerID = 32, FreelancerID = 110, IsViewed = true },
new ChatBox { ChatBoxID = 56, EmployerID = 39, FreelancerID = 107, IsViewed = true },
new ChatBox { ChatBoxID = 57, EmployerID = 28, FreelancerID = 110, IsViewed = true },
new ChatBox { ChatBoxID = 58, EmployerID = 25, FreelancerID = 105, IsViewed = true },
new ChatBox { ChatBoxID = 59, EmployerID = 32, FreelancerID = 102, IsViewed = true },
new ChatBox { ChatBoxID = 60, EmployerID = 33, FreelancerID = 106, IsViewed = true },
new ChatBox { ChatBoxID = 61, EmployerID = 33, FreelancerID = 106, IsViewed = true },
new ChatBox { ChatBoxID = 62, EmployerID = 27, FreelancerID = 107, IsViewed = true },
new ChatBox { ChatBoxID = 63, EmployerID = 38, FreelancerID = 105, IsViewed = true },
new ChatBox { ChatBoxID = 64, EmployerID = 37, FreelancerID = 109, IsViewed = true },
new ChatBox { ChatBoxID = 65, EmployerID = 23, FreelancerID = 102, IsViewed = true },
new ChatBox { ChatBoxID = 66, EmployerID = 39, FreelancerID = 103, IsViewed = true },
new ChatBox { ChatBoxID = 67, EmployerID = 38, FreelancerID = 102, IsViewed = true },
new ChatBox { ChatBoxID = 68, EmployerID = 26, FreelancerID = 109, IsViewed = true },
new ChatBox { ChatBoxID = 69, EmployerID = 25, FreelancerID = 107, IsViewed = true },
new ChatBox { ChatBoxID = 70, EmployerID = 23, FreelancerID = 110, IsViewed = true },
new ChatBox { ChatBoxID = 71, EmployerID = 33, FreelancerID = 107, IsViewed = true },
new ChatBox { ChatBoxID = 72, EmployerID = 36, FreelancerID = 108, IsViewed = true },
new ChatBox { ChatBoxID = 73, EmployerID = 37, FreelancerID = 101, IsViewed = true },
new ChatBox { ChatBoxID = 74, EmployerID = 23, FreelancerID = 108, IsViewed = true },
new ChatBox { ChatBoxID = 75, EmployerID = 30, FreelancerID = 101, IsViewed = true },
new ChatBox { ChatBoxID = 76, EmployerID = 27, FreelancerID = 106, IsViewed = true },
new ChatBox { ChatBoxID = 77, EmployerID = 34, FreelancerID = 101, IsViewed = true },
new ChatBox { ChatBoxID = 78, EmployerID = 22, FreelancerID = 102, IsViewed = true },
new ChatBox { ChatBoxID = 79, EmployerID = 25, FreelancerID = 105, IsViewed = true },
new ChatBox { ChatBoxID = 80, EmployerID = 39, FreelancerID = 109, IsViewed = true },
new ChatBox { ChatBoxID = 81, EmployerID = 28, FreelancerID = 107, IsViewed = true },
new ChatBox { ChatBoxID = 82, EmployerID = 38, FreelancerID = 102, IsViewed = true },
new ChatBox { ChatBoxID = 83, EmployerID = 32, FreelancerID = 107, IsViewed = true },
new ChatBox { ChatBoxID = 84, EmployerID = 32, FreelancerID = 102, IsViewed = true },
new ChatBox { ChatBoxID = 85, EmployerID = 32, FreelancerID = 106, IsViewed = true },
new ChatBox { ChatBoxID = 86, EmployerID = 26, FreelancerID = 106, IsViewed = true },
new ChatBox { ChatBoxID = 87, EmployerID = 24, FreelancerID = 110, IsViewed = true },
new ChatBox { ChatBoxID = 88, EmployerID = 37, FreelancerID = 106, IsViewed = true },
new ChatBox { ChatBoxID = 89, EmployerID = 30, FreelancerID = 106, IsViewed = true },
new ChatBox { ChatBoxID = 90, EmployerID = 27, FreelancerID = 108, IsViewed = true },
new ChatBox { ChatBoxID = 91, EmployerID = 34, FreelancerID = 104, IsViewed = true },
new ChatBox { ChatBoxID = 92, EmployerID = 32, FreelancerID = 108, IsViewed = true },
new ChatBox { ChatBoxID = 93, EmployerID = 28, FreelancerID = 108, IsViewed = true },
new ChatBox { ChatBoxID = 94, EmployerID = 40, FreelancerID = 103, IsViewed = true },
new ChatBox { ChatBoxID = 95, EmployerID = 22, FreelancerID = 103, IsViewed = true },
new ChatBox { ChatBoxID = 96, EmployerID = 21, FreelancerID = 103, IsViewed = true },
new ChatBox { ChatBoxID = 97, EmployerID = 27, FreelancerID = 106, IsViewed = true },
new ChatBox { ChatBoxID = 98, EmployerID = 29, FreelancerID = 104, IsViewed = true },
new ChatBox { ChatBoxID = 99, EmployerID = 22, FreelancerID = 103, IsViewed = true },
new ChatBox { ChatBoxID = 100, EmployerID = 29, FreelancerID = 101, IsViewed = true },
new ChatBox { ChatBoxID = 101, EmployerID = 37, FreelancerID = 108, IsViewed = false },
new ChatBox { ChatBoxID = 102, EmployerID = 31, FreelancerID = 103, IsViewed = false },
new ChatBox { ChatBoxID = 103, EmployerID = 36, FreelancerID = 106, IsViewed = false },
new ChatBox { ChatBoxID = 104, EmployerID = 21, FreelancerID = 104, IsViewed = false },
new ChatBox { ChatBoxID = 105, EmployerID = 26, FreelancerID = 108, IsViewed = false },
new ChatBox { ChatBoxID = 106, EmployerID = 37, FreelancerID = 108, IsViewed = false },
new ChatBox { ChatBoxID = 107, EmployerID = 31, FreelancerID = 110, IsViewed = false },
new ChatBox { ChatBoxID = 108, EmployerID = 38, FreelancerID = 104, IsViewed = false },
new ChatBox { ChatBoxID = 109, EmployerID = 35, FreelancerID = 105, IsViewed = false },
new ChatBox { ChatBoxID = 110, EmployerID = 22, FreelancerID = 110, IsViewed = false },
new ChatBox { ChatBoxID = 111, EmployerID = 35, FreelancerID = 102, IsViewed = false },
new ChatBox { ChatBoxID = 112, EmployerID = 29, FreelancerID = 107, IsViewed = false },
new ChatBox { ChatBoxID = 113, EmployerID = 31, FreelancerID = 102, IsViewed = false },
new ChatBox { ChatBoxID = 114, EmployerID = 20, FreelancerID = 109, IsViewed = false },
new ChatBox { ChatBoxID = 115, EmployerID = 30, FreelancerID = 105, IsViewed = false },
new ChatBox { ChatBoxID = 116, EmployerID = 26, FreelancerID = 108, IsViewed = false },
new ChatBox { ChatBoxID = 117, EmployerID = 27, FreelancerID = 104, IsViewed = false },
new ChatBox { ChatBoxID = 118, EmployerID = 22, FreelancerID = 106, IsViewed = false },
new ChatBox { ChatBoxID = 119, EmployerID = 33, FreelancerID = 108, IsViewed = false },
new ChatBox { ChatBoxID = 120, EmployerID = 32, FreelancerID = 109, IsViewed = false },
new ChatBox { ChatBoxID = 121, EmployerID = 22, FreelancerID = 103, IsViewed = false },
new ChatBox { ChatBoxID = 122, EmployerID = 31, FreelancerID = 106, IsViewed = false },
new ChatBox { ChatBoxID = 123, EmployerID = 37, FreelancerID = 103, IsViewed = false },
new ChatBox { ChatBoxID = 124, EmployerID = 26, FreelancerID = 105, IsViewed = false },
new ChatBox { ChatBoxID = 125, EmployerID = 35, FreelancerID = 108, IsViewed = false },
new ChatBox { ChatBoxID = 126, EmployerID = 33, FreelancerID = 108, IsViewed = false },
new ChatBox { ChatBoxID = 127, EmployerID = 25, FreelancerID = 108, IsViewed = false },
new ChatBox { ChatBoxID = 128, EmployerID = 20, FreelancerID = 104, IsViewed = false },
new ChatBox { ChatBoxID = 129, EmployerID = 34, FreelancerID = 109, IsViewed = false },
new ChatBox { ChatBoxID = 130, EmployerID = 31, FreelancerID = 103, IsViewed = false },
new ChatBox { ChatBoxID = 131, EmployerID = 24, FreelancerID = 107, IsViewed = false },
new ChatBox { ChatBoxID = 132, EmployerID = 24, FreelancerID = 101, IsViewed = false },
new ChatBox { ChatBoxID = 133, EmployerID = 34, FreelancerID = 103, IsViewed = false },
new ChatBox { ChatBoxID = 134, EmployerID = 36, FreelancerID = 103, IsViewed = false },
new ChatBox { ChatBoxID = 135, EmployerID = 38, FreelancerID = 107, IsViewed = false },
new ChatBox { ChatBoxID = 136, EmployerID = 27, FreelancerID = 104, IsViewed = false },
new ChatBox { ChatBoxID = 137, EmployerID = 27, FreelancerID = 102, IsViewed = false },
new ChatBox { ChatBoxID = 138, EmployerID = 21, FreelancerID = 104, IsViewed = false },
new ChatBox { ChatBoxID = 139, EmployerID = 24, FreelancerID = 107, IsViewed = false },
new ChatBox { ChatBoxID = 140, EmployerID = 33, FreelancerID = 101, IsViewed = false },
new ChatBox { ChatBoxID = 141, EmployerID = 40, FreelancerID = 106, IsViewed = false },
new ChatBox { ChatBoxID = 142, EmployerID = 37, FreelancerID = 109, IsViewed = false },
new ChatBox { ChatBoxID = 143, EmployerID = 28, FreelancerID = 109, IsViewed = false },
new ChatBox { ChatBoxID = 144, EmployerID = 26, FreelancerID = 105, IsViewed = false },
new ChatBox { ChatBoxID = 145, EmployerID = 33, FreelancerID = 103, IsViewed = false },
new ChatBox { ChatBoxID = 146, EmployerID = 24, FreelancerID = 109, IsViewed = false },
new ChatBox { ChatBoxID = 147, EmployerID = 36, FreelancerID = 104, IsViewed = false },
new ChatBox { ChatBoxID = 148, EmployerID = 24, FreelancerID = 106, IsViewed = false },
new ChatBox { ChatBoxID = 149, EmployerID = 35, FreelancerID = 102, IsViewed = false },
new ChatBox { ChatBoxID = 150, EmployerID = 36, FreelancerID = 103, IsViewed = false },
new ChatBox { ChatBoxID = 151, EmployerID = 38, FreelancerID = 104, IsViewed = false },
new ChatBox { ChatBoxID = 152, EmployerID = 37, FreelancerID = 102, IsViewed = false },
new ChatBox { ChatBoxID = 153, EmployerID = 31, FreelancerID = 104, IsViewed = false },
new ChatBox { ChatBoxID = 154, EmployerID = 33, FreelancerID = 110, IsViewed = false },
new ChatBox { ChatBoxID = 155, EmployerID = 35, FreelancerID = 106, IsViewed = false },
new ChatBox { ChatBoxID = 156, EmployerID = 30, FreelancerID = 104, IsViewed = false },
new ChatBox { ChatBoxID = 157, EmployerID = 22, FreelancerID = 110, IsViewed = false },
new ChatBox { ChatBoxID = 158, EmployerID = 26, FreelancerID = 107, IsViewed = false },
new ChatBox { ChatBoxID = 159, EmployerID = 21, FreelancerID = 108, IsViewed = false },
new ChatBox { ChatBoxID = 160, EmployerID = 37, FreelancerID = 102, IsViewed = false },
new ChatBox { ChatBoxID = 161, EmployerID = 35, FreelancerID = 110, IsViewed = false },
new ChatBox { ChatBoxID = 162, EmployerID = 34, FreelancerID = 104, IsViewed = false },
new ChatBox { ChatBoxID = 163, EmployerID = 29, FreelancerID = 101, IsViewed = false },
new ChatBox { ChatBoxID = 164, EmployerID = 20, FreelancerID = 108, IsViewed = false },
new ChatBox { ChatBoxID = 165, EmployerID = 22, FreelancerID = 102, IsViewed = false },
new ChatBox { ChatBoxID = 166, EmployerID = 31, FreelancerID = 108, IsViewed = false },
new ChatBox { ChatBoxID = 167, EmployerID = 24, FreelancerID = 107, IsViewed = false },
new ChatBox { ChatBoxID = 168, EmployerID = 28, FreelancerID = 110, IsViewed = false },
new ChatBox { ChatBoxID = 169, EmployerID = 28, FreelancerID = 107, IsViewed = false },
new ChatBox { ChatBoxID = 170, EmployerID = 23, FreelancerID = 106, IsViewed = false },
new ChatBox { ChatBoxID = 171, EmployerID = 32, FreelancerID = 103, IsViewed = false },
new ChatBox { ChatBoxID = 172, EmployerID = 23, FreelancerID = 110, IsViewed = false },
new ChatBox { ChatBoxID = 173, EmployerID = 33, FreelancerID = 106, IsViewed = false },
new ChatBox { ChatBoxID = 174, EmployerID = 24, FreelancerID = 104, IsViewed = false },
new ChatBox { ChatBoxID = 175, EmployerID = 40, FreelancerID = 110, IsViewed = false },
new ChatBox { ChatBoxID = 176, EmployerID = 38, FreelancerID = 110, IsViewed = false },
new ChatBox { ChatBoxID = 177, EmployerID = 31, FreelancerID = 105, IsViewed = false },
new ChatBox { ChatBoxID = 178, EmployerID = 37, FreelancerID = 108, IsViewed = false },
new ChatBox { ChatBoxID = 179, EmployerID = 23, FreelancerID = 102, IsViewed = false },
new ChatBox { ChatBoxID = 180, EmployerID = 30, FreelancerID = 110, IsViewed = false },
new ChatBox { ChatBoxID = 181, EmployerID = 29, FreelancerID = 101, IsViewed = false },
new ChatBox { ChatBoxID = 182, EmployerID = 40, FreelancerID = 105, IsViewed = false },
new ChatBox { ChatBoxID = 183, EmployerID = 31, FreelancerID = 103, IsViewed = false },
new ChatBox { ChatBoxID = 184, EmployerID = 34, FreelancerID = 106, IsViewed = false },
new ChatBox { ChatBoxID = 185, EmployerID = 27, FreelancerID = 106, IsViewed = false },
new ChatBox { ChatBoxID = 186, EmployerID = 22, FreelancerID = 102, IsViewed = false },
new ChatBox { ChatBoxID = 187, EmployerID = 36, FreelancerID = 103, IsViewed = false },
new ChatBox { ChatBoxID = 188, EmployerID = 25, FreelancerID = 103, IsViewed = false },
new ChatBox { ChatBoxID = 189, EmployerID = 23, FreelancerID = 106, IsViewed = false },
new ChatBox { ChatBoxID = 190, EmployerID = 20, FreelancerID = 109, IsViewed = false },
new ChatBox { ChatBoxID = 191, EmployerID = 28, FreelancerID = 108, IsViewed = false },
new ChatBox { ChatBoxID = 192, EmployerID = 29, FreelancerID = 105, IsViewed = false },
new ChatBox { ChatBoxID = 193, EmployerID = 25, FreelancerID = 106, IsViewed = false },
new ChatBox { ChatBoxID = 194, EmployerID = 20, FreelancerID = 108, IsViewed = false },
new ChatBox { ChatBoxID = 195, EmployerID = 28, FreelancerID = 102, IsViewed = false },
new ChatBox { ChatBoxID = 196, EmployerID = 40, FreelancerID = 109, IsViewed = false },
new ChatBox { ChatBoxID = 197, EmployerID = 22, FreelancerID = 107, IsViewed = false },
new ChatBox { ChatBoxID = 198, EmployerID = 34, FreelancerID = 103, IsViewed = false },
new ChatBox { ChatBoxID = 199, EmployerID = 28, FreelancerID = 105, IsViewed = false },
new ChatBox { ChatBoxID = 200, EmployerID = 26, FreelancerID = 106, IsViewed = false }
);
        }
    }
}
