// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpusLink.Entity;

#nullable disable

namespace OpusLink.Entity.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OpusLink.Entity.Models.BlockWordRegEx", b =>
                {
                    b.Property<int>("PatternID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatternID"), 1L, 1);

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("PatternID");

                    b.ToTable("BlockWordRegEx", (string)null);
                });

            modelBuilder.Entity("OpusLink.Entity.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("CategoryParentID")
                        .HasColumnType("int");

                    b.HasKey("CategoryID");

                    b.HasIndex("CategoryParentID");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("OpusLink.Entity.Models.ChatBox", b =>
                {
                    b.Property<int>("ChatBoxID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChatBoxID"), 1L, 1);

                    b.Property<int>("EmployerID")
                        .HasColumnType("int");

                    b.Property<int>("FreelancerID")
                        .HasColumnType("int");

                    b.Property<bool>("IsViewed")
                        .HasColumnType("bit");

                    b.HasKey("ChatBoxID");

                    b.HasIndex("EmployerID");

                    b.HasIndex("FreelancerID");

                    b.ToTable("ChatBox", (string)null);
                });

            modelBuilder.Entity("OpusLink.Entity.Models.FeedbackUser", b =>
                {
                    b.Property<int>("FeedbackUserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackUserID"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreateByUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("Star")
                        .HasColumnType("int");

                    b.Property<int>("TargetToUserID")
                        .HasColumnType("int");

                    b.HasKey("FeedbackUserID");

                    b.HasIndex("CreateByUserID");

                    b.HasIndex("TargetToUserID");

                    b.ToTable("FeedbackUser", (string)null);
                });

            modelBuilder.Entity("OpusLink.Entity.Models.FreelancerWithSkill", b =>
                {
                    b.Property<int>("FreelancerWithSkillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FreelancerWithSkillID"), 1L, 1);

                    b.Property<int>("FreelancerID")
                        .HasColumnType("int");

                    b.Property<int>("SkillID")
                        .HasColumnType("int");

                    b.HasKey("FreelancerWithSkillID");

                    b.HasIndex("FreelancerID");

                    b.HasIndex("SkillID");

                    b.ToTable("FreelancerWithSkill", (string)null);
                });

            modelBuilder.Entity("OpusLink.Entity.Models.HistoryPayment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentID"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransactionCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("PaymentID");

                    b.HasIndex("UserID");

                    b.ToTable("HistoryPayment", (string)null);
                });

            modelBuilder.Entity("OpusLink.Entity.Models.Job", b =>
                {
                    b.Property<int>("JobID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobID"), 1L, 1);

                    b.Property<decimal?>("BudgetFrom")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BudgetTo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployerID")
                        .HasColumnType("int");

                    b.Property<int?>("FreelancerID")
                        .HasColumnType("int");

                    b.Property<string>("JobContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("LocationID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("JobID");

                    b.HasIndex("EmployerID");

                    b.HasIndex("FreelancerID");

                    b.HasIndex("LocationID");

                    b.ToTable("Job", (string)null);
                });

            modelBuilder.Entity("OpusLink.Entity.Models.JobInCategory", b =>
                {
                    b.Property<int>("JobInCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobInCategoryID"), 1L, 1);

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<int>("JobID")
                        .HasColumnType("int");

                    b.HasKey("JobInCategoryID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("JobID");

                    b.ToTable("JobInCategory", (string)null);
                });

            modelBuilder.Entity("OpusLink.Entity.Models.Location", b =>
                {
                    b.Property<int>("LocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationID"), 1L, 1);

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("LocationID");

                    b.ToTable("Location", (string)null);
                });

            modelBuilder.Entity("OpusLink.Entity.Models.Message", b =>
                {
                    b.Property<int>("MessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageID"), 1L, 1);

                    b.Property<int>("ChatBoxID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FromEmployer")
                        .HasColumnType("bit");

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("MessageID");

                    b.HasIndex("ChatBoxID");

                    b.ToTable("Message", (string)null);
                });

            modelBuilder.Entity("OpusLink.Entity.Models.Milestone", b =>
                {
                    b.Property<int>("MilestoneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MilestoneID"), 1L, 1);

                    b.Property<decimal>("AmountToPay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilePathFreelancerUpload")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("JobID")
                        .HasColumnType("int");

                    b.Property<string>("MilestoneContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MilestoneID");

                    b.HasIndex("JobID");

                    b.ToTable("Milestone", (string)null);
                });

            modelBuilder.Entity("OpusLink.Entity.Models.Notification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationID"), 1L, 1);

                    b.Property<bool>("IsReaded")
                        .HasColumnType("bit");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NotificationContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NotificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("NotificationID");

                    b.HasIndex("UserID");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("OpusLink.Entity.Models.Offer", b =>
                {
                    b.Property<int>("OfferID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfferID"), 1L, 1);

                    b.Property<DateTime>("DateOffer")
                        .HasColumnType("datetime2");

                    b.Property<string>("EstimatedPlan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("ExpectedDays")
                        .HasColumnType("smallint");

                    b.Property<int>("FreelancerID")
                        .HasColumnType("int");

                    b.Property<int>("JobID")
                        .HasColumnType("int");

                    b.Property<decimal>("ProposedCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SelfIntroduction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OfferID");

                    b.HasIndex("FreelancerID");

                    b.HasIndex("JobID");

                    b.ToTable("Offer", (string)null);
                });

            modelBuilder.Entity("OpusLink.Entity.Models.ReportJob", b =>
                {
                    b.Property<int>("ReportJobID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportJobID"), 1L, 1);

                    b.Property<int>("CreateByFreelancer")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReportJobContent")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("TargetToJob")
                        .HasColumnType("int");

                    b.HasKey("ReportJobID");

                    b.HasIndex("TargetToJob");

                    b.ToTable("ReportJob", (string)null);
                });

            modelBuilder.Entity("OpusLink.Entity.Models.ReportUser", b =>
                {
                    b.Property<int>("ReportUserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportUserID"), 1L, 1);

                    b.Property<int>("CreateByUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReportUserContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TargetToUserID")
                        .HasColumnType("int");

                    b.HasKey("ReportUserID");

                    b.HasIndex("CreateByUserID");

                    b.HasIndex("TargetToUserID");

                    b.ToTable("ReportUser", (string)null);
                });

            modelBuilder.Entity("OpusLink.Entity.Models.SaveJob", b =>
                {
                    b.Property<int>("SaveJobID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaveJobID"), 1L, 1);

                    b.Property<int>("FreelancerID")
                        .HasColumnType("int");

                    b.Property<int>("JobID")
                        .HasColumnType("int");

                    b.HasKey("SaveJobID");

                    b.HasIndex("JobID");

                    b.ToTable("SaveJob", (string)null);
                });

            modelBuilder.Entity("OpusLink.Entity.Models.SearchJobForm", b =>
                {
                    b.Property<int>("FormID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormID"), 1L, 1);

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<int>("LocationID")
                        .HasColumnType("int");

                    b.HasKey("FormID");

                    b.ToTable("SearchJobForm", (string)null);
                });

            modelBuilder.Entity("OpusLink.Entity.Models.Skill", b =>
                {
                    b.Property<int>("SkillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillID"), 1L, 1);

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("SkillParentID")
                        .HasColumnType("int");

                    b.HasKey("SkillID");

                    b.HasIndex("SkillParentID");

                    b.ToTable("Skill", (string)null);
                });

            modelBuilder.Entity("OpusLink.Entity.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal?>("AmountMoney")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BankAccountInfor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CVFilePath")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullNameOnIDCard")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("IDNumber")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Introduction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVeryfiedIdentity")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePicture")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("StarMedium")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("OpusLink.Entity.Models.WithdrawRequest", b =>
                {
                    b.Property<int>("WithdrawRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WithdrawRequestID"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("WithdrawRequestID");

                    b.HasIndex("UserID");

                    b.ToTable("WithdrawRequest", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("OpusLink.Entity.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("OpusLink.Entity.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpusLink.Entity.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("OpusLink.Entity.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpusLink.Entity.Models.Category", b =>
                {
                    b.HasOne("OpusLink.Entity.Models.Category", "CategoryParent")
                        .WithMany()
                        .HasForeignKey("CategoryParentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CategoryParent");
                });

            modelBuilder.Entity("OpusLink.Entity.Models.ChatBox", b =>
                {
                    b.HasOne("OpusLink.Entity.Models.User", "Employer")
                        .WithMany("ChatBoxsAsAnEmployer")
                        .HasForeignKey("EmployerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpusLink.Entity.Models.User", "Freelancer")
                        .WithMany("ChatBoxsAsAFreelancer")
                        .HasForeignKey("FreelancerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employer");

                    b.Navigation("Freelancer");
                });

            modelBuilder.Entity("OpusLink.Entity.Models.FeedbackUser", b =>
                {
                    b.HasOne("OpusLink.Entity.Models.User", "CreateByUser")
                        .WithMany("FeedbackUsersAsACreater")
                        .HasForeignKey("CreateByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpusLink.Entity.Models.User", "TargetToUser")
                        .WithMany("FeedbackUsersAsATargeter")
                        .HasForeignKey("TargetToUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreateByUser");

                    b.Navigation("TargetToUser");
                });

            modelBuilder.Entity("OpusLink.Entity.Models.FreelancerWithSkill", b =>
                {
                    b.HasOne("OpusLink.Entity.Models.User", "Freelancer")
                        .WithMany("FreelancerWithSkills")
                        .HasForeignKey("FreelancerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpusLink.Entity.Models.Skill", "Skill")
                        .WithMany("FreelancerWithSkills")
                        .HasForeignKey("SkillID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Freelancer");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("OpusLink.Entity.Models.HistoryPayment", b =>
                {
                    b.HasOne("OpusLink.Entity.Models.User", "User")
                        .WithMany("HistoryPayments")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OpusLink.Entity.Models.Job", b =>
                {
                    b.HasOne("OpusLink.Entity.Models.User", "Employer")
                        .WithMany("JobsAsAnEmployer")
                        .HasForeignKey("EmployerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpusLink.Entity.Models.User", "Freelancer")
                        .WithMany("JobsAsAFreelancer")
                        .HasForeignKey("FreelancerID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OpusLink.Entity.Models.Location", "Location")
                        .WithMany("Jobs")
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employer");

                    b.Navigation("Freelancer");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("OpusLink.Entity.Models.JobInCategory", b =>
                {
                    b.HasOne("OpusLink.Entity.Models.Category", "Category")
                        .WithMany("JobInCategories")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpusLink.Entity.Models.Job", "Job")
                        .WithMany("JobInCategories")
                        .HasForeignKey("JobID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("OpusLink.Entity.Models.Message", b =>
                {
                    b.HasOne("OpusLink.Entity.Models.ChatBox", "ChatBox")
                        .WithMany("Messages")
                        .HasForeignKey("ChatBoxID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChatBox");
                });

            modelBuilder.Entity("OpusLink.Entity.Models.Milestone", b =>
                {
                    b.HasOne("OpusLink.Entity.Models.Job", "Job")
                        .WithMany("Milestones")
                        .HasForeignKey("JobID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("OpusLink.Entity.Models.Notification", b =>
                {
                    b.HasOne("OpusLink.Entity.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OpusLink.Entity.Models.Offer", b =>
                {
                    b.HasOne("OpusLink.Entity.Models.User", "Freelancer")
                        .WithMany("OffersAsAFreelancer")
                        .HasForeignKey("FreelancerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpusLink.Entity.Models.Job", "Job")
                        .WithMany("Offers")
                        .HasForeignKey("JobID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Freelancer");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("OpusLink.Entity.Models.ReportJob", b =>
                {
                    b.HasOne("OpusLink.Entity.Models.User", "Freelancer")
                        .WithMany("ReportJobs")
                        .HasForeignKey("TargetToJob")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpusLink.Entity.Models.Job", "Job")
                        .WithMany("ReportJobs")
                        .HasForeignKey("TargetToJob")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Freelancer");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("OpusLink.Entity.Models.ReportUser", b =>
                {
                    b.HasOne("OpusLink.Entity.Models.User", "CreateByUser")
                        .WithMany("ReportUsersAsACreater")
                        .HasForeignKey("CreateByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpusLink.Entity.Models.User", "TargetToUser")
                        .WithMany("ReportUsersAsATargeter")
                        .HasForeignKey("TargetToUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreateByUser");

                    b.Navigation("TargetToUser");
                });

            modelBuilder.Entity("OpusLink.Entity.Models.SaveJob", b =>
                {
                    b.HasOne("OpusLink.Entity.Models.User", "Freelancer")
                        .WithMany("SaveJobs")
                        .HasForeignKey("JobID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpusLink.Entity.Models.Job", "Job")
                        .WithMany("SaveJobs")
                        .HasForeignKey("JobID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Freelancer");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("OpusLink.Entity.Models.Skill", b =>
                {
                    b.HasOne("OpusLink.Entity.Models.Skill", "SkillParent")
                        .WithMany()
                        .HasForeignKey("SkillParentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SkillParent");
                });

            modelBuilder.Entity("OpusLink.Entity.Models.WithdrawRequest", b =>
                {
                    b.HasOne("OpusLink.Entity.Models.User", "User")
                        .WithMany("WithdrawRequests")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OpusLink.Entity.Models.Category", b =>
                {
                    b.Navigation("JobInCategories");
                });

            modelBuilder.Entity("OpusLink.Entity.Models.ChatBox", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("OpusLink.Entity.Models.Job", b =>
                {
                    b.Navigation("JobInCategories");

                    b.Navigation("Milestones");

                    b.Navigation("Offers");

                    b.Navigation("ReportJobs");

                    b.Navigation("SaveJobs");
                });

            modelBuilder.Entity("OpusLink.Entity.Models.Location", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("OpusLink.Entity.Models.Skill", b =>
                {
                    b.Navigation("FreelancerWithSkills");
                });

            modelBuilder.Entity("OpusLink.Entity.Models.User", b =>
                {
                    b.Navigation("ChatBoxsAsAFreelancer");

                    b.Navigation("ChatBoxsAsAnEmployer");

                    b.Navigation("FeedbackUsersAsACreater");

                    b.Navigation("FeedbackUsersAsATargeter");

                    b.Navigation("FreelancerWithSkills");

                    b.Navigation("HistoryPayments");

                    b.Navigation("JobsAsAFreelancer");

                    b.Navigation("JobsAsAnEmployer");

                    b.Navigation("Notifications");

                    b.Navigation("OffersAsAFreelancer");

                    b.Navigation("ReportJobs");

                    b.Navigation("ReportUsersAsACreater");

                    b.Navigation("ReportUsersAsATargeter");

                    b.Navigation("SaveJobs");

                    b.Navigation("WithdrawRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
